version: "3.9"
services:
  gateway:
    build: ./gateway
    ports:
      - "7000:7000"
    expose:
      - 7000
      - 7001
    depends_on:
      - dealership_auth
    volumes:
      - ./gateway:/usr/src/app

  dealership_auth:
    build: ./dealership_auth
    ports:
      - "0.0.0.0:7001:7001"
    expose:
      - 7000
      - 7001
    depends_on:
      - dealership_auth_db
      - dealership_auth_redis
    volumes:
      - ./dealership_auth:/usr/src/app

  dealership_auth_db:
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    image: postgres:latest
    ports:
      - "0.0.0.0:7201:5432"

  dealership_auth_redis:
    image: redis:latest
    ports:
      - "0.0.0.0:7202:6379"
    expose:
      - 7202
