version: "3"
services:
  gateway:
    build:
      context: ./gateway
      target: dev
    environment:
      NODE_ENV: ${NODE_ENV}
      GRAPHQL_DEV: ${GRAPHQL_DEV}
      ORIGIN_LINK: ${ORIGIN_LINK}
    ports:
      - "7000:7000"
    expose:
      - 7000
    depends_on:
      - dealership_auth
    volumes:
      - ./gateway:/usr/src/app

  dealership_auth:
    build:
      context: ./dealership_auth
      target: dev
    environment:
      NODE_ENV: ${NODE_ENV}
      GRAPHQL_DEV: ${GRAPHQL_DEV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
    ports:
      - "7001:7001"
    expose:
      - 7001
    depends_on:
      - dealership_auth_db
      - dealership_auth_redis
    volumes:
      - ./dealership_auth:/usr/src/app

  dealership_auth_db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=db
    image: postgres:latest
    ports:
      - "7201:5432"

  dealership_auth_redis:
    image: redis:latest
    ports:
      - "0.0.0.0:7202:6379"
    expose:
      - 7202
